ALTER TABLE Result
MODIFY COLUMN Event VARCHAR(128);

ALTER TABLE Result
MODIFY COLUMN NOC VARCHAR(4);

ALTER TABLE OlympicGames
MODIFY COLUMN Season VARCHAR(6);

ALTER TABLE OlympicGames
MODIFY COLUMN City VARCHAR(23);

ALTER TABLE Event
MODIFY COLUMN Event VARCHAR(128);

ALTER TABLE Event
MODIFY COLUMN Gender VARCHAR(2);

ALTER TABLE Country
MODIFY COLUMN NOC VARCHAR(4);

ALTER TABLE Country
MODIFY COLUMN FullName VARCHAR(33);

ALTER TABLE City
MODIFY COLUMN City VARCHAR(24);

ALTER TABLE City
MODIFY COLUMN NOC VARCHAR(4);


-- Rename because incorrectly done
-- ALTER TABLE CitizenOf
-- RENAME COLUMN NOC TO Country;
ALTER TABLE CitizenOf
MODIFY COLUMN Country VARCHAR(76);

ALTER TABLE Athlete
MODIFY COLUMN Name VARCHAR(55);

ALTER TABLE Athlete
MODIFY COLUMN Born_date DATETIME;

ALTER TABLE Athlete
MODIFY COLUMN Born_country VARCHAR(10);